version: '3.8'
services:
  app:
    build: .
    ports:
      - "3080:3080"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: