version: '3.8'
services:
  app:
    container_name: app
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/node/app
    env_file:
      - .env
    command: >
      sh -c "
      echo 'Waiting for db to become healthy...';
      while ! pg_isready -h db -U ${POSTGRES_USER}; do
        sleep 2;
      done;
      echo 'db is ready, starting app...';
      npm start;
      "
  db:
    container_name: db
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: